### ISSUE TITLE
undefined method `link_to' for #<Hint:0x00007f4058393010>

### ISSUE THREAD

**Issue by KoleckoOrg** [mfrodl/kolecko#75]
In:
`  after_create do
    message_text = "Nová nápověda k šifře "
    message_text << link_to(hint_request.puzzle.full_name,
                            Rails.application.routes.url_helpers.hint_requests_path)
    message = Message.new(text: message_text)
    TeamMessage.create(message: message, team: hint_request.team)
`

Am I missing some stuff locally, or is this maybe a configuration issue?
The code in question was introduced in c49ff0f81a34f6b8bd02c79bf85f500a6d1471bc

**Comment by KoleckoOrg** [comment]
BTW This happens when I  submit a new hint.
